# Generated by Django 6.0.3 on 2026-03-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_plantao', models.IntegerField()),
                ('data_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_saida', models.TimeField()),
                ('assistido', models.TextField()),
                ('publicacoes', models.TextField(blank=True, null=True)),
                ('procedimento', models.TextField(blank=True, null=True)),
                ('movimentacao_processual', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('numero_processo', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='aberto', max_length=20)),
                ('status_avaliacao', models.CharField(default='pendente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
            ],
        ),
    ]
