# Generated by Django 6.0.3 on 2026-03-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='numero_plantao',
            field=models.IntegerField(editable=False),
        ),
    ]
