# Generated by Django 6.0.3 on 2026-03-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N1', models.FloatField(blank=True, null=True)),
                ('N2', models.FloatField(blank=True, null=True)),
                ('N3', models.FloatField(blank=True, null=True)),
                ('N4', models.FloatField(blank=True, null=True)),
                ('N5', models.FloatField(blank=True, null=True)),
                ('N6', models.FloatField(blank=True, null=True)),
                ('N7', models.FloatField(blank=True, null=True)),
                ('N8', models.FloatField(blank=True, null=True)),
                ('N9', models.FloatField(blank=True, null=True)),
                ('N10', models.FloatField(blank=True, null=True)),
                ('N11', models.FloatField(blank=True, null=True)),
                ('N12', models.FloatField(blank=True, null=True)),
                ('N13', models.FloatField(blank=True, null=True)),
                ('N14', models.FloatField(blank=True, null=True)),
                ('N15', models.FloatField(blank=True, null=True)),
                ('N16', models.FloatField(blank=True, null=True)),
                ('N17', models.FloatField(blank=True, null=True)),
                ('N18', models.FloatField(blank=True, null=True)),
                ('N19', models.FloatField(blank=True, null=True)),
                ('N20', models.FloatField(blank=True, null=True)),
                ('NSUM1', models.FloatField(blank=True, null=True)),
                ('NSUM2', models.FloatField(blank=True, null=True)),
                ('NSUM3', models.FloatField(blank=True, null=True)),
                ('NSUM4', models.FloatField(blank=True, null=True)),
                ('NSUM5', models.FloatField(blank=True, null=True)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantoes.plantao')),
            ],
        ),
    ]
