# Generated by Django 6.0.3 on 2026-03-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='NSUM1',
            new_name='SUM1',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='NSUM2',
            new_name='SUM2',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='NSUM3',
            new_name='SUM3',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='NSUM4',
            new_name='SUM4',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='NSUM5',
            new_name='SUM5',
        ),
    ]
