# Generated by Django 6.0.3 on 2026-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('disciplina', models.CharField(max_length=200)),
                ('periodo_letivo', models.CharField(max_length=20)),
                ('turma_turno', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
